ascii version

diff --git a/cpzot b/cpzot
--- a/cpzot
+++ b/cpzot
@@ -1,1 +1,73 @@
-{Zaa¢{{@©£z@¨@@¢@@¢¨¢£@£@£¥@£¨{éÆâÉÕâãÉÄ~}©¢¢£}ÃÁÓÓÅÙÈÖÔÅ~[ÈÖÔÅéÖãÙÖÖã~a©@Z@¢¤@`¥@^@£@@@}Åz@è¤@@£@@¤£©@£@¢¤@£@¤@£¢@}@nPò@@§£@ô¢¤¢£~[M¢¤@`]@­@[o@`£@ð@½^@£@@@}Åz@è¤@@£@@@£@¢£@¢@¨¤@@¤£©@£@¢¤}@nPò@@§£@ô{{@Ô@¢¤@£@ò@}}@@ò@}}@¢¤@¢@@¥{~¢@Z@@[À¢¤¢£Ð@O@@`@M[ÀéÆâÉÕâãÉÄÐ]@ÕÖ×ÁââæÄz@aa@`@[éÖãÙÖÖãaa©@^@£@@@Åz@è¤@@£@@@£@¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[éÖãÙÖÖãaa©@nPò@@~£¤@Z@@[À¢¤¢£Ð@O@@`@M[ÀéÆâÉÕâãÉÄÐ]@ÕÖ×ÁââæÄz@aa@`@[éÖãÙÖÖãaa©@^@£@@@Åz@è¤@@£@@@£@¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[éÖãÙÖÖãaa©@nPò@@~£¤@Z@@[À¢¤¢£Ð@O@@`@M[ÀéÆâÉÕâãÉÄÐ]@ÕÖ×ÁââæÄz@aa@`@[ÀÃÁÓÓÅÙÈÖÔÅÐa©@[éÖãÙÖÖãaa@^@£@@@Åz@è¤@@£@@@£@¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[ÀÃÁÓÓÅÙÈÖÔÅÐa©@[éÖãÙÖÖãaa@nPò@@~£¤@Z@@[À¢¤¢£Ð@O@@`@M[ÀéÆâÉÕâãÉÄÐ]@ÕÖ×ÁââæÄz@aa@`@[ÀÃÁÓÓÅÙÈÖÔÅÐa©@[éÖãÙÖÖãaa@^@£@@@Åz@è¤@@£@@@£@¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[ÀÃÁÓÓÅÙÈÖÔÅÐa©@[éÖãÙÖÖãaa@nPò@@~£¤@[^@£@@@Åz@¤¢@¥¢¤@£@@£¢@¥@@¤@¢@@£@¤¢@£@[ÃÁÓÓÅÙÈÖÔÅ@nPò@@§£@ô{{@Ä£@££@£¨@£@¨@£K@ã¢@¢@£@@m£m@¤£¨@@@[éÖãÙÖÖãa{@Z@££~[M@[éÖãÙÖÖãa@òna¥a¤@PP@@[×æÄ]@^@£@@@Åz@ä@£@£@[éÖãÙÖÖãa@£¨K@Ã¤£@¢@¥K@nPò@@§£@ô@­@§[À££Ð@~@§[ÀéÖãÙÖÖãÐa@½^@£@@££~[ÀéÖãÙÖÖãÐaa@­@§[À££Ð@~@§[ÀéÖãÙÖÖãÐa@½^@£@@££~[ÀéÖãÙÖÖãÐaa¢@@@Åz@¢¨@@@[ÀéÖãÙÖÖãÐa@¢@£@£@£@[ÀéÖãÙÖÖãÐa@@[ÀéÖãÙÖÖãÐa@nPò@@§£@ô@Z@¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[À££Ð©@^@£@@@Åz@}¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[À££Ð©}@K@ã¢@¢@£@§£K@nPò@@§£@ô@Z@¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[ÀÃÁÓÓÅÙÈÖÔÅÐa©@[À££Ð@^@£@@@Åz@}¢¤@`¤@[ÀéÆâÉÕâãÉÄÐ@aa@`@[ÀÃÁÓÓÅÙÈÖÔÅÐa©@[À££Ð}@K@ã¢@¢@£@§£K@nPò@@§£@ô§£@ð
+#!/bin/sh
+
+#
+# cpzot: copy from callers file system to inactive directory
+#
+
+ZFSINSTID='zfsinst'
+CALLERHOME=$HOME
+ZOTROOT="/zopenprod"
+
+if ! sudo -v ; then
+  echo 'Error: You need to be authorized to sudo to run this program' >&2
+  exit 4
+fi
+sudolist=$(sudo -l)
+if [ $? -gt 0 ]; then
+  echo 'Error: You need to be able to list commands you are authorized to sudo' >&2
+  exit 4
+fi
+
+#
+# Make sure the 2 'rm' and 2 'cp' sudo commands are available
+#
+err=false
+if ! echo "${sudolist}" | grep -q "(${ZFSINSTID}) NOPASSWD: /bin/rm -rf $ZOTROOT/locala/zopenprod" ; then
+  echo "Error: You need to be able to sudo -u ${ZFSINSTID} /bin/rm -rf $ZOTROOT/locala/zopenprod" >&2
+  err=true
+fi
+if ! echo "${sudolist}" | grep -q "(${ZFSINSTID}) NOPASSWD: /bin/rm -rf $ZOTROOT/localb/zopenprod" ; then
+  echo "Error: You need to be able to sudo -u ${ZFSINSTID} /bin/rm -rf $ZOTROOT/localb/zopenprod" >&2
+  err=true
+fi
+if ! echo "${sudolist}" | grep -q "(${ZFSINSTID}) NOPASSWD: /bin/cp -rf ${CALLERHOME}/zopenprod $ZOTROOT/locala/" ; then
+  echo "Error: You need to be able to sudo -u ${ZFSINSTID} /bin/cp -rf ${CALLERHOME}/zopenprod $ZOTROOT/locala/" >&2
+  err=true
+fi
+if ! echo "${sudolist}" | grep -q "(${ZFSINSTID}) NOPASSWD: /bin/cp -rf ${CALLERHOME}/zopenprod $ZOTROOT/localb/" ; then
+  echo "Error: You need to be able to sudo -u ${ZFSINSTID} /bin/cp -rf ${CALLERHOME}/zopenprod $ZOTROOT/localb/" >&2
+  err=true
+fi
+
+if $err; then
+  echo "Error: use visudo to add this privilege or run as a different user than $CALLERHOME" >&2
+  exit 4
+fi
+
+#
+# Determine target directory to copy to. This is the one _not_ currently linked from $ZOTROOT/local
+#
+if ! target=$(cd $ZOTROOT/local 2>/dev/null && echo $PWD) ; then
+  echo "Error: Unable to determine $ZOTROOT/local directory. Configuration is invalid." >&2
+  exit 4
+fi
+
+if [ "x${target}" = "x${ZOTROOT}/locala" ]; then
+  cptgt="${ZOTROOT}/localb/"
+elif [ "x${target}" = "x${ZOTROOT}/localb" ]; then
+  cptgt="${ZOTROOT}/locala/"
+else
+  echo "Error: symbolic link for ${ZOTROOT}/local does not point to ${ZOTROOT}/locala nor ${ZOTROOT}/localb" >&2
+  exit 4
+fi
+
+if ! sudo -u ${ZFSINSTID} /bin/rm -rf "${cptgt}zopenprod" ; then
+  echo "Error: 'sudo -u ${ZFSINSTID} /bin/rm -rf ${cptgt}zopenprod' failed. This is not expected." >&2
+  exit 4
+fi
+if ! sudo -u ${ZFSINSTID} /bin/cp -rf "${CALLERHOME}/zopenprod" "${cptgt}" ; then
+  echo "Error: 'sudo -u ${ZFSINSTID} /bin/cp -rf ${CALLERHOME}/zopenprod ${cptgt}' failed. This is not expected." >&2
+  exit 4
+fi
+
+exit 0
diff --git a/upgradezot b/upgradezot
--- a/upgradezot
+++ b/upgradezot
@@ -1,1 +1,64 @@
-{Zaa¢{{@¤©£z@¤¢@£@©aÖâ@Ö@ã¢@@£@¢@[ÈÖÔÅa©£@£¨{@@@¨@@£@¦@¢£¢@M@@¤£@¢¨¢£k@£¢@¦¤@@@¤¨]{@{@@`¢@[éÖ×ÅÕmÙÖÖãÆâaKKa©@[ÈÖÔÅa©@@@@@{@¢£@¤@@@a©@£@@}©}@£{@©`£@`¨@[ÈÖÔÅa©@@@@@@@@@@@@@@@@@@@@@{@£@¤£@¤@£@{@¤@¢@£@@éÖ×ÅÕmÙÖãÆâ@@£@a¤¢aa©{@¤@©£@£@¨@[ÈÖÔÅa©@£@@¤£@£{@¤@¢¦©£@£@¢¦@@¤£@£@@¤£@¤@a¤¢aa©{ÔèÄÉÙ~[M@[M@[ð]@n@a¥a¤@ònPñ@PP@¦@`×]éÖãÙÖÖã~[ÀéÖ×ÅÕmÙÖÖãÆâÐaKKa©@Z@­@`@[ÀéÖ×ÅÕmÙÖÖãÆâÐ@½@OO@Z@­@`@[ÀéÖãÙÖÖãÐ@½^@£@@@Åz@Õ@£@¥@¤@©`@mm@@£@¥@£@à[éÖ×ÅÕmÙÖÖãÆâaKKa©@¤£@£¨@nPò@@§£@ô@­@`@[ÈÖÔÅa©@½^@£@@@Z@©~[M@[ÈÖÔÅa©@òna¥a¤@PP@@[×æÄ]@^@£@@@@@Åz@[ÈÖÔÅa©@§¢£¢@¤£@¢@£@@¢¨@K@nPò@@@@§£@ô@@¢@@@@Z@@`¢@[éÖ×ÅÕmÙÖÖãÆâaKKa©@[ÈÖÔÅa©@^@£@@@@@Åz@ä@£@£@©@¢¨@@@@£¨K@nPò@@@@§£@ô@@@Z@@`@[ÈÖÔÅa©a\@^@£@@@Åz@ä@£@@¤@[ÈÖÔÅa©@@£K@nPò@@§£@ô@Z@©`£@`¨@[ÈÖÔÅa©@^@£@@@Åz@×£@£@[ÈÖÔÅa©@K@nPò@@§£@ô¦£§£~[Maa¢@¢zéÖ×ÅÕmÙÖÖãÆâ~à[ÈÖÔÅa©àzéÖ×ÅÕmÙÖÖãÆâ~àa¤¢aa©àz@[ÈÖÔÅa©a£a©`]@­@[o@`£@ð@½^@£@@@Åz@ä@£@¤£@éÖ×ÅÕmÙÖÖãÆâ@@£@£@©@@nPò@@§£@ô@Z@@[À¦£§£Ð@n[ÈÖÔÅa©a£a©`@^@£@@@Åz@ä@£@¤£@[ÈÖÔÅa©a£a©`@nPò@@§£@ô@Z@[ÔèÄÉÙa©£@^@£@@@Åz@ä@£@¨@¢@£@@¤£@nPò@@§£@ô@Z@[ÔèÄÉÙa¢¦©£@^@£@@@Åz@ä@£@¢¦@¤£@£@@¤@nPò@@§£@ô§£@ð
+#!/bin/sh
+
+#
+# upgradezot: upgrades the z/OS Open Tools from the callers $HOME/zot directory
+#   by performing the following steps (on a production system, this would be done manually)
+# 
+# ln -s $ZOPEN_ROOTFS/../zopenprod $HOME/zopenprod     # set up link from home/zopenprod to a 'zopenprod' location
+# zopen-promote -y $HOME/zopenprod                     # promote current build into 
+# run sed to change ZOPEN_ROTFS line to /usr/local/zopenprod
+# run cpzot to copy $HOME/zopenprod to offline production tree
+# run swapzot to swap offline production to online production under /usr/local/zopenprod
+#
+MYDIR="$(cd "$(dirname "$0")" > /dev/null 2>&1 && pwd -P)"
+
+ZOTROOT="${ZOPEN_ROOTFS}/../zopenprod"
+
+if ! [ -d "${ZOPEN_ROOTFS}" ] || ! [ -d "${ZOTROOT}" ]; then
+  echo "Error: Need to have run zopen-config _and_ need to have created \$ZOPEN_ROOTFS/../zopenprod production directory" >&2
+  exit 4
+fi
+
+if [ -e $HOME/zopenprod ]; then
+  if ! zopenprod=$(cd $HOME/zopenprod 2>/dev/null && echo $PWD) ; then
+    echo "Error: $HOME/zopenprod exists but is not a symbolic link." >&2
+    exit 4
+  fi
+else 
+  if ! ln -s $ZOPEN_ROOTFS/../zopenprod $HOME/zopenprod ; then
+    echo "Error: Unable to create zopenprod symbolic link from home directory." >&2
+    exit 4
+  fi
+fi
+
+if ! rm -rf $HOME/zopenprod/* ; then
+  echo "Error: Unable to clean up $HOME/zopenprod before promotion." >&2
+  exit 4
+fi
+
+if ! zopen-promote -y $HOME/zopenprod ; then
+  echo "Error: Promotion to $HOME/zopenprod failed." >&2
+  exit 4
+fi
+
+newtext=$(/bin/sed "s:ZOPEN_ROOTFS=\"$HOME/zopenprod\":ZOPEN_ROOTFS=\"/usr/local/zopenprod\":" "$HOME/zopenprod/etc/zopen-config")
+if [ $? -gt 0 ]; then
+  echo "Error: Unable to update ZOPEN_ROOTFS in the promoted zopenprod code" >&2
+  exit 4
+fi
+if ! echo "${newtext}" >"$HOME/zopenprod/etc/zopen-config" ; then
+  echo "Error: Unable to update $HOME/zopenprod/etc/zopen-config" >&2
+  exit 4
+fi
+
+if ! $MYDIR/cpzot ; then
+  echo "Error: Unable to copy files to offline production" >&2
+  exit 4
+fi
+
+if ! $MYDIR/swapzot ; then
+  echo "Error: Unable to swap production tree for upgrade" >&2
+  exit 4
+fi
+
+exit 0
